choco install vscode -y
choco install notepadplusplus -y
choco install googlechrome -y
choco install firefox -y
choco install vlc -y
choco install git -y
choco install putty.install -y
choco install python -y
choco install keepass.install -y